DELETE http://localhost:3001/api/persons/64eee09b2acf6b3067a4b215

###
GET http://localhost:3001/api/persons/

###
POST http://localhost:3001/api/persons/ 
content-type: application/json

{ 
    "name": "lizan", 
    "number": "90-9090"
}

###
GET http://localhost:3001/persons